### ISSUE TITLE
about improvements (Compilation issues on Linux)

### ISSUE THREAD

**Issue by tissatussa** [pkrisz99/Renegade#39]
hi, i just compiled your newest main source and i succeeded, but i had to adjust the Makefile for Linux. That file contains a warning, stating it's experimental .. why ? You should take some time learning how to create a proper Makefile for all OS, otherwise people can't use the engine, or they must download the asset (but there's none for Apple).

In 'Search.cpp' i read :

---

_This is the main search code of Renegade. If you're reading this, you're probably interested in what this engine does, and I'm happy for that, feel free to try some ideas from here!_

_However, you may have confidence in this code, but be aware, that I don't. Here are some caveats:_

_- this engine does not reduce losing captures at all_
_- LMR is quite conservative_
_- the ordering score can come either directly from history, or from captures/killers etc._
_- quiescence search is very basic_
_- there aren't any form of staged movegen implemented_
_- elo gain estimates are very outdated_
_- some stuff are just plain cursed_

---

The current CCRL list shows your engine has rating 3552, which is impressive .. i wonder how it can improve when you focus on the above shortcomings !

**Comment by pkrisz99** [comment]
Hi, there's a few things to unpack here:

**Makefile:**
- You said that you needed to modify the makefile to get it working. What error did you see, and what did you need to change?
- The makefile *should* support compiling for Apple hardware, but I don't have any to test it.
- The note about being experimental is over a year old, I've just forgot about it. However, I want to rewrite the makefile soon (just to look nicer), so until then the warning will stay.

**Comments:**
These are intended for other engine developers to help understanding and to clear up some possible confusion. Sure, the tone of it maybe sounds a bit pessimistic, but that's just a manifestation of my perfectionism. It's really not that bad.

**Improvements:**
I'm usually quite busy, and the time I want to spend on Renegade is limited. I will try ideas that I find interesting, rather than solely focusing on strength. The development version should be a good amount stronger already.

**Comment by tissatussa** [comment]
i had this error in `Reporting.cpp` :

```
Reporting.cpp:80:91: error: no member named 'SelDepth' in 'SearchStatistics'
   80 |         output = "info depth " + std::to_string(e.depth) + " seldepth " + std::to_string(e.stats.SelDepth)
      |                                                                                          ~~~~~~~ ^
```

i solved it by changing the concerning code like this :

```
// output = "info depth " + std::to_string(e.depth) + " seldepth " + std::to_string(e.stats.SelDepth)
output = "info depth " + std::to_string(e.depth) + " seldepth " + std::to_string(e.seldepth)
	// + " score " + score + wdlOutput + " nodes " + std::to_string(e.stats.Nodes) + " nps " + std::to_string(e.nps)
	+ " score " + score + wdlOutput + " nodes " + std::to_string(e.nodes) + " nps " + std::to_string(e.nps)
	+ " time " + std::to_string(e.time) + " hashfull " + std::to_string(e.hashfull)
	+ " pv" + pvString;
```

i also changed the makefile for Linux : [makefile-fixed-for-linux.zip](https://github.com/user-attachments/files/16456446/makefile-fixed-for-linux.zip)

**Comment by pkrisz99** [comment]
The error is `Reporting.cpp` is a good catch, I overlooked that part when making a change there.  
I'll look into the makefile soon.

**Comment by pkrisz99** [comment]
5da4be9 fixes the syntax error, and on my local Ubuntu installation the code compiles just fine without any additional changes to the makefile. I'm closing this issue now, and reopen it if needed.
